# Generated by Django 4.1.5 on 2023-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_auto_20220302_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='middlename',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='address',
        ),
        migrations.AddField(
            model_name='employees',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='lastname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
